### ISSUE TITLE
VCheck-NSX  Report Save Locally 

### ISSUE THREAD

**Issue by kakollu007** [vCheckReport/vCheck-NSX#12]
Hi Team , 

First of all i would like to appreciate the effort you guys put in this project . 

My question is ...! is there any way that VCheck-NSX  generated Report Save Local machine . I am planning to implement this feature in my test environment first which has no internet to route the generated report to Email id .

Please help me with the above .

Regards,
Kakollu Kumar

**Comment by alanrenouf** [comment]
It saves locally to $ENV:Temp by default.
