### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kakollu007** [vCheckReport/vCheck-NSX#13]
Hi All,

I am getting below error. Please let me know how to proceed further  

![error](https://user-images.githubusercontent.com/34521259/37313829-ec8adfd6-2676-11e8-9bf6-c8a3fe073a9a.PNG)

**Comment by alanrenouf** [comment]
Issue was to do with user connecting to vc with :443 and therefore the filename was trying to include the : in the filename and failing.

Workaround was to not specify the :443 as that was the default anyway.
