### ISSUE TITLE
Does vcheck-NSX code support both NSX-V and NSX-T?

### ISSUE THREAD

**Issue by mohammedamirk** [vCheckReport/vCheck-NSX#18]
Hi,
I would like to know. does vcheck-NSX code support both NSX-V and NSX-T versions?

**Comment by lucdekens** [comment]
PowerCLI currently only supports NSX-T.

So only NSX-T.

**Comment by vScripter** [comment]
@mohammedamirk Howdy; this plugin was originally created for NSX-V and uses the PowerNSX module. This project hasn't been worked on in a while and was in the early stages of development when it was published, thus, it's pretty dated. Being that NSX-T is the future, any future development on this will probably be geared towards NSX-T.

I'm going to close this one out.
